// Issue catalog — one entry per AuditChecklist key. When a check is FALSE
// in the checklist, the corresponding catalog entry surfaces as an
// AuditIssue. Wording follows compliance rules: "could", "potential",
// "based on visible signals" — no guarantees, no fake numbers.

import type { IssueCatalog } from "./types";

export const ISSUE_CATALOG: IssueCatalog = {
  // ── Website basics ──────────────────────────────────────────────────
  hasModernDesign: {
    title: "Outdated visual design",
    severity: "medium",
    dimension: "website",
    whyItMatters: "First impressions form within seconds. A dated visual style can quietly lower trust before anyone reads a word.",
    likelyImpact: "Could be reducing conversion rates and time-on-site.",
    suggestedFix: "Refresh typography, spacing, and colour palette. Move to a current design system or rebuild on a modern stack if needed.",
    difficulty: "medium",
    implementation: { minHours: 8, maxHours: 24 },
    outreachAngle: "Mention that the visual design feels dated — easiest objection to surface without sounding negative.",
    clientFriendlyExplanation: "Your site looks dated, which can make visitors trust you less even if your service is excellent. A visual refresh signals an active, modern business.",
  },
  isMobileFriendly: {
    title: "Not mobile-friendly",
    severity: "high",
    dimension: "website",
    whyItMatters: "Most local searches happen on phones. A broken mobile layout means visitors bounce before they ever read your offer.",
    likelyImpact: "Could be losing the majority of mobile visitors.",
    suggestedFix: "Implement a responsive layout. Test on real devices. Ensure tap targets are 48px+ and font sizes 16px+.",
    difficulty: "medium",
    implementation: { minHours: 6, maxHours: 16 },
    outreachAngle: "Open by noting their mobile experience needs work — a high-impact, easy-to-defend critique.",
    clientFriendlyExplanation: "Most people find local businesses on their phone. Right now your site is hard to use on mobile, which means you may be losing customers before they ever reach the booking step.",
  },
  loadsFast: {
    title: "Slow loading time",
    severity: "high",
    dimension: "website",
    whyItMatters: "Page speed affects both visitor patience and Google ranking. Each extra second of load time measurably increases bounce.",
    likelyImpact: "Could be costing visitors and search visibility.",
    suggestedFix: "Compress images (WebP/AVIF), defer non-critical scripts, enable caching, move to faster hosting if needed.",
    difficulty: "easy",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Show their PageSpeed score — concrete, third-party, hard to dismiss.",
    clientFriendlyExplanation: "Your site loads slowly. People expect pages to open in under three seconds; longer than that and they leave. This also affects your Google ranking.",
  },
  hasClearCTA: {
    title: "Missing clear call-to-action",
    severity: "high",
    dimension: "website",
    whyItMatters: "Without a clear next step, visitors who would have engaged simply leave. The single highest-leverage UX fix.",
    likelyImpact: "Could be losing interested visitors who don't know what to do next.",
    suggestedFix: "Add one prominent primary action above the fold (Book Now / Get a Quote / Call). Repeat at logical points down the page.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 5 },
    outreachAngle: "Walk through the homepage and ask what the intended next step is — usually unclear.",
    clientFriendlyExplanation: "Visitors land on your site and don't know what to do next. Adding a clear primary action — like 'Book Now' — is one of the highest-impact changes you can make.",
  },
  hasContactForm: {
    title: "No online contact form",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Some visitors aren't ready to call. A form captures intent that would otherwise be lost.",
    likelyImpact: "Could be missing leads who prefer not to phone.",
    suggestedFix: "Add a 3-field contact form (name / email / message). Auto-acknowledgement email helps.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Note that the only contact option is a phone number — limiting in 2026.",
    clientFriendlyExplanation: "Some customers don't want to call until they have more info. A simple contact form catches those leads who would otherwise leave without contacting you.",
  },
  hasPhoneVisible: {
    title: "Phone number not visible above the fold",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Local visitors often want to call. Hidden phone numbers create friction.",
    likelyImpact: "Could be missing impatient or mobile-first visitors.",
    suggestedFix: "Display the phone number prominently in the header. On mobile, make it a tap-to-call link.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Mention that the phone number is hard to find — most visitors won't scroll to find it.",
    clientFriendlyExplanation: "Your phone number is hard to find. For a local business, the phone is often the fastest path to a booking — making it visible everywhere is a quick win.",
  },
  hasGoogleMapsLink: {
    title: "No Google Maps / address link",
    severity: "low",
    dimension: "website",
    whyItMatters: "Customers often verify a business is real by checking the map and reviews.",
    likelyImpact: "Could be reducing trust for first-time visitors.",
    suggestedFix: "Embed a Google Map of the location, or link to the Google Business Profile.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Tie this together with their Google Business Profile state.",
    clientFriendlyExplanation: "Adding a map helps customers verify you're real and find you easily. It's a small change that can increase trust noticeably.",
  },
  hasTrustSignals: {
    title: "No reviews or trust signals",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Reviews are the single strongest persuasion lever for local services.",
    likelyImpact: "Could be losing visitors comparing you to competitors who DO show reviews.",
    suggestedFix: "Embed Google review widget, or feature 3–5 customer testimonials on the homepage.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Reviews are persuasion gold — easy add, big visible difference.",
    clientFriendlyExplanation: "Customers compare you to competitors. If their site shows reviews and yours doesn't, you start every comparison at a disadvantage.",
  },
  hasServicePages: {
    title: "No dedicated service pages",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Each service is a separate search intent. Bundling everything onto one page misses dozens of long-tail keywords.",
    likelyImpact: "Could be limiting search visibility for individual services.",
    suggestedFix: "Create one page per main service with focused copy and a service-specific CTA.",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 12 },
    outreachAngle: "Pair with the local SEO angle — service pages are the SEO foundation.",
    clientFriendlyExplanation: "Right now Google sees one page about everything. With a separate page for each service, each can rank for its own searches.",
  },
  hasCityLandingPage: {
    title: "No city / region landing page",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "Local businesses compete on '[service] in [city]' searches. Without a city-targeted page, you're fighting national results.",
    likelyImpact: "Could be missing local search opportunities.",
    suggestedFix: "Create a [Service] in [City] page targeting the area, with location-specific copy and reviews.",
    difficulty: "medium",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Frame as missing local SEO opportunity — concrete and local-specific.",
    clientFriendlyExplanation: "When someone searches '[your service] in [your city]', you want to be the answer. A dedicated local page tells Google you specifically serve that area.",
  },

  // ── SEO ─────────────────────────────────────────────────────────────
  hasLocalSEOTitle: {
    title: "Page title doesn't mention city + service",
    severity: "high",
    dimension: "seo",
    whyItMatters: "Title tags are the single strongest local-SEO signal Google reads.",
    likelyImpact: "Could be invisible for local searches that should be easy wins.",
    suggestedFix: "Rewrite to format: '[Service] in [City] — [Business Name]'.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "View Source the homepage — the missing local title is concrete and easy to show.",
    clientFriendlyExplanation: "Your page title — what shows up in Google's blue link — doesn't mention what you do or where you do it. That's the first signal Google uses to rank you locally.",
  },
  hasMetaDescription: {
    title: "No meta description",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "Without a meta description, Google writes its own — usually poorly. Affects click-through, not rank directly.",
    likelyImpact: "Could be losing search clicks even when ranking is acceptable.",
    suggestedFix: "Write a 150-character description featuring main service, city, and a soft hook.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Easy quick-win addition — pair with title fix.",
    clientFriendlyExplanation: "The grey text Google shows under your link is auto-generated and often unhelpful. Writing it yourself improves click-through.",
  },
  hasH1: {
    title: "Missing or duplicate H1 heading",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "H1 tells Google what each page is primarily about. Missing H1 is a basic SEO miss.",
    likelyImpact: "Could be hurting page-level ranking signals.",
    suggestedFix: "Set one descriptive H1 per page that names the service or topic.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Bundle with overall heading-structure cleanup.",
    clientFriendlyExplanation: "Each page should clearly tell Google what it's about. A single, descriptive heading at the top does that.",
  },
  hasHeadingStructure: {
    title: "Inconsistent heading hierarchy",
    severity: "low",
    dimension: "seo",
    whyItMatters: "H1 → H2 → H3 helps both screen readers and Google parse content.",
    likelyImpact: "Could be subtly hurting accessibility and SEO.",
    suggestedFix: "Restructure headings: one H1, H2 per section, H3 per sub-section.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Polish item — bundle into a broader content-cleanup project.",
    clientFriendlyExplanation: "Headings on your site are inconsistent, which makes the page harder for Google and accessibility tools to understand.",
  },
  hasLocalKeywords: {
    title: "Local keywords missing from copy",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "If your copy doesn't mention the city or area, you're competing nationally instead of locally.",
    likelyImpact: "Could be missing easy local search wins.",
    suggestedFix: "Naturally weave the city, neighborhoods, and region into the body copy. Don't keyword-stuff.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Show the homepage doesn't mention the city — concrete proof.",
    clientFriendlyExplanation: "Your copy doesn't mention your city. When someone searches '[service] in [your city]', Google wants pages that actually mention that city.",
  },
  hasInternalLinks: {
    title: "Few or no internal links",
    severity: "low",
    dimension: "seo",
    whyItMatters: "Internal links spread ranking power and increase time-on-site.",
    likelyImpact: "Could be limiting how Google crawls and ranks the site.",
    suggestedFix: "Link related service pages and city pages to each other in the body content.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Polish item — package with broader SEO sprint.",
    clientFriendlyExplanation: "Linking related pages of your own site helps Google understand which content matters and keeps visitors browsing longer.",
  },
  isIndexable: {
    title: "Site appears blocked from search engines",
    severity: "critical",
    dimension: "seo",
    whyItMatters: "If Google can't index the site, it can't rank for anything. The single most catastrophic SEO failure.",
    likelyImpact: "Site may be invisible in search entirely.",
    suggestedFix: "Remove noindex meta and robots.txt blocks. Submit sitemap to Search Console. Verify crawl in Search Console URL Inspection.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Critical — lead with this. It's the kind of finding that grabs immediate attention.",
    clientFriendlyExplanation: "Your site appears to be telling Google not to show it. This is the most important fix on the list — without it nothing else matters.",
  },
  hasSchemaMarkup: {
    title: "No LocalBusiness schema markup",
    severity: "low",
    dimension: "seo",
    whyItMatters: "Schema markup unlocks rich results in Google (hours, reviews, address).",
    likelyImpact: "Could be missing rich-result opportunities competitors are using.",
    suggestedFix: "Add LocalBusiness JSON-LD with hours, address, phone, geo, and review schema.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Show competitors with rich results — concrete differentiation.",
    clientFriendlyExplanation: "Adding structured data tells Google detailed info about your business — hours, phone, address — which can show directly in search results.",
  },
  hasGoogleBusinessProfile: {
    title: "Google Business Profile gap",
    severity: "critical",
    dimension: "seo",
    whyItMatters: "GBP is the single most important local-SEO asset. Unclaimed or empty profiles are the biggest local visibility miss.",
    likelyImpact: "Could be invisible in Google Maps and local-pack results.",
    suggestedFix: "Claim the profile, complete every field, add 10+ photos, fill services, request 5+ reviews from existing customers.",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 12 },
    outreachAngle: "Lead with this for any local business. Universal need, big visible impact.",
    clientFriendlyExplanation: "Your Google Business Profile — the panel that shows up next to your listing in search — needs work. This is the single biggest local-search lever for any business.",
  },

  // ── Conversion ──────────────────────────────────────────────────────
  hasClearOffer: {
    title: "Offer not clear within 5 seconds",
    severity: "high",
    dimension: "conversion",
    whyItMatters: "If a visitor can't tell what you sell within seconds, they leave. The most expensive UX problem.",
    likelyImpact: "Could be reducing engagement on every page view.",
    suggestedFix: "Rewrite the hero so service + audience + value are obvious in one sentence.",
    difficulty: "medium",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Open the page and ask: in 5 seconds, what does this business do? Answer is usually unclear.",
    clientFriendlyExplanation: "When someone lands on your homepage, they should know within five seconds what you do, who it's for, and why they should care. Right now that's not obvious.",
  },
  lowContactFriction: {
    title: "Contact takes too many steps",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "Every extra field or click loses a percentage of leads. Friction is the silent killer of conversion.",
    likelyImpact: "Could be losing leads who started but didn't finish reaching out.",
    suggestedFix: "Shorten contact to 3 fields max. Add a one-click phone CTA on mobile.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Walk the contact path together — usually 5+ steps.",
    clientFriendlyExplanation: "Right now reaching out to you takes more steps than it needs to. Each extra step quietly loses a percentage of leads.",
  },
  lowBookingFriction: {
    title: "Booking requires manual back-and-forth",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "Self-service booking captures customers outside business hours and reduces admin.",
    likelyImpact: "Could be losing after-hours bookings entirely.",
    suggestedFix: "Add an online booking widget for the most common service.",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 8 },
    outreachAngle: "Frame as both a customer experience and time-saving win.",
    clientFriendlyExplanation: "Customers can't book themselves; they have to email or call. That means losing the ones who decide late at night, and creating extra admin for you.",
  },
  hasAboveFoldCTA: {
    title: "Primary CTA hidden below the fold",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "Most visitors don't scroll. A CTA below the fold is essentially invisible to half the audience.",
    likelyImpact: "Could be losing visitors who don't scroll.",
    suggestedFix: "Move the main CTA into the hero section, visible without scrolling.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Open on desktop AND mobile — show the missing CTA in both views.",
    clientFriendlyExplanation: "The action you want visitors to take needs to be visible without scrolling. Right now they have to scroll to find it — many won't.",
  },
  hasMobileCTA: {
    title: "No sticky / tap-to-call CTA on mobile",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "Mobile users won't scroll back to a top CTA. A persistent bottom action keeps the path open.",
    likelyImpact: "Could be losing mobile visitors who give up scrolling.",
    suggestedFix: "Add a sticky tap-to-call or Book Now button at the bottom of the mobile viewport.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Concrete and mobile-specific — easy demo.",
    clientFriendlyExplanation: "On mobile, the action button disappears as soon as visitors scroll. A sticky bottom button keeps the path to contacting you always visible.",
  },
  hasLeadCapture: {
    title: "No soft lead capture",
    severity: "low",
    dimension: "conversion",
    whyItMatters: "Most visitors aren't ready to commit. A soft capture (free quote / newsletter) catches the in-between.",
    likelyImpact: "Could be losing the 90 % of visitors not ready to buy.",
    suggestedFix: "Add a free-quote or estimate-request form as a lower-commitment alternative.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Frame as catching long-tail leads who'd otherwise vanish.",
    clientFriendlyExplanation: "Most visitors aren't ready to book today. Offering something low-commitment — like a free quote — captures the ones who would otherwise leave with nothing.",
  },

  // ── Automation ──────────────────────────────────────────────────────
  hasBookingAutomation: {
    title: "No online booking system",
    severity: "high",
    dimension: "automation",
    whyItMatters: "Manual booking burns hours and limits when customers can self-serve.",
    likelyImpact: "Could be losing 24/7 booking opportunities + costing you admin hours.",
    suggestedFix: "Set up a booking widget (Calendly / Setmore / Square / niche-specific tool).",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 8 },
    outreachAngle: "Lead with the time savings — usually 5+ hours per week back.",
    clientFriendlyExplanation: "Right now every booking needs a back-and-forth. An online booking widget lets customers self-serve outside business hours and saves you several hours a week.",
  },
  hasQuoteAutomation: {
    title: "No quote request automation",
    severity: "medium",
    dimension: "automation",
    whyItMatters: "Quote requests left waiting go cold. Auto-acknowledgement keeps them warm.",
    likelyImpact: "Could be losing quote leads to faster competitors.",
    suggestedFix: "Build a quote-request form with auto-reply confirming receipt + expected response time.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Frame as 'never let a lead go cold' — universally appealing.",
    clientFriendlyExplanation: "When someone requests a quote, they want immediate confirmation. An automatic acknowledgement keeps them engaged while you prepare the actual reply.",
  },
  hasInvoiceAutomation: {
    title: "Manual invoicing",
    severity: "medium",
    dimension: "automation",
    whyItMatters: "Manual invoices delay payment and consume admin time.",
    likelyImpact: "Could be slowing cash flow + adding hours of bookkeeping per week.",
    suggestedFix: "Connect Stripe / Xero / QuickBooks to auto-generate and send invoices on completion.",
    difficulty: "medium",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Time + cash-flow angle — both quantifiable.",
    clientFriendlyExplanation: "Manual invoicing slows you down and delays payment. Connecting an automated tool gets invoices out instantly and reduces the admin loop.",
  },
  hasReminderEmails: {
    title: "No appointment reminders",
    severity: "low",
    dimension: "automation",
    whyItMatters: "No-shows are expensive. Automated reminders typically cut them by 30–50 %.",
    likelyImpact: "Could be costing revenue per missed appointment.",
    suggestedFix: "Add SMS / email reminders 24h before each appointment via the booking system.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Easy ROI calculation — reminders pay for themselves quickly.",
    clientFriendlyExplanation: "When customers forget appointments, you lose the slot AND the revenue. Automated reminders reduce no-shows significantly with no manual effort.",
  },
  hasFollowUpAutomation: {
    title: "No lead follow-up automation",
    severity: "medium",
    dimension: "automation",
    whyItMatters: "Most leads don't reply to the first message. Without follow-up they're lost.",
    likelyImpact: "Could be losing leads who would have converted on a second touch.",
    suggestedFix: "Add a 2-step email sequence for leads who don't reply within 3 days.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 5 },
    outreachAngle: "Frame as catching the leads who slip through the cracks.",
    clientFriendlyExplanation: "Most leads don't reply on the first try. A simple two-step follow-up automation catches the ones who needed a gentle reminder.",
  },
  hasAnalytics: {
    title: "No analytics installed",
    severity: "low",
    dimension: "automation",
    whyItMatters: "Without analytics, every marketing decision is guesswork.",
    likelyImpact: "Could be making decisions blind.",
    suggestedFix: "Install GA4 + Google Search Console. Add event tracking for key CTAs.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Quick foundational fix — bundle into any project.",
    clientFriendlyExplanation: "Right now there's no way to see what's working on your site. Adding analytics lets you decide based on real data instead of guessing.",
  },
  hasInternalDashboard: {
    title: "No team dashboard",
    severity: "low",
    dimension: "automation",
    whyItMatters: "A small dashboard surfacing today's bookings, leads, and key numbers saves daily friction.",
    likelyImpact: "Could be wasting admin time hunting for daily info.",
    suggestedFix: "Build a small internal dashboard showing today's bookings + recent leads in one view.",
    difficulty: "medium",
    implementation: { minHours: 6, maxHours: 16 },
    outreachAngle: "Premium add-on — focus on bigger clients.",
    clientFriendlyExplanation: "A simple shared dashboard for your team — today's bookings, recent leads, key numbers — saves daily friction and gives everyone the same view.",
  },
};
