// Native Dutch business phrasing — calm, professional, direct.
// NOT a literal translation of the English catalog.
// Keeps compliance language: "kan", "mogelijk", "op basis van zichtbare signalen".

import type { IssueCatalog } from "./types";

export const ISSUE_CATALOG_NL: IssueCatalog = {
  // ── Website basics ──────────────────────────────────────────────────
  hasModernDesign: {
    title: "Verouderd visueel ontwerp",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Een eerste indruk vormt zich in seconden. Een gedateerd ontwerp kan bezoekers onbewust minder vertrouwen geven, nog voor ze iets gelezen hebben.",
    likelyImpact: "Kan de conversie en betrokkenheid drukken.",
    suggestedFix: "Ververs typografie, ruimte en kleurpalet. Eventueel overstappen op een modern ontwerpsysteem of een herbouw indien nodig.",
    difficulty: "medium",
    implementation: { minHours: 8, maxHours: 24 },
    outreachAngle: "Begin met de observatie dat het visuele ontwerp gedateerd aandoet — een zachte, makkelijk te onderbouwen ingang.",
    clientFriendlyExplanation: "De site oogt gedateerd, wat bezoekers onbewust minder vertrouwen kan geven, ongeacht de kwaliteit van de dienst. Een visuele opfrissing geeft direct een actiever en moderner gevoel.",
  },
  isMobileFriendly: {
    title: "Niet mobielvriendelijk",
    severity: "high",
    dimension: "website",
    whyItMatters: "De meeste lokale zoekopdrachten gebeuren op telefoons. Een gebroken mobiele weergave zorgt ervoor dat bezoekers afhaken voordat ze überhaupt het aanbod zien.",
    likelyImpact: "Kan een groot deel van de mobiele bezoekers verliezen.",
    suggestedFix: "Implementeer een responsive layout. Test op echte apparaten. Zorg voor tap-targets van 48px+ en lettertypes van 16px+.",
    difficulty: "medium",
    implementation: { minHours: 6, maxHours: 16 },
    outreachAngle: "Begin met de mobiele ervaring — concrete, makkelijk te demonstreren kritiek met grote impact.",
    clientFriendlyExplanation: "De meeste mensen vinden lokale bedrijven via hun telefoon. De site is op dit moment lastig te gebruiken op mobiel, wat betekent dat klanten kunnen afhaken nog vóór ze bij de boekingsstap komen.",
  },
  loadsFast: {
    title: "Trage laadtijd",
    severity: "high",
    dimension: "website",
    whyItMatters: "Snelheid beïnvloedt zowel het geduld van bezoekers als de positie in Google. Elke extra seconde laadtijd verhoogt het bouncepercentage merkbaar.",
    likelyImpact: "Kan bezoekers en zichtbaarheid in zoekresultaten kosten.",
    suggestedFix: "Comprimeer afbeeldingen (WebP/AVIF), stel niet-kritieke scripts uit, schakel caching in, kies indien nodig snellere hosting.",
    difficulty: "easy",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Laat de PageSpeed-score zien — concreet, onafhankelijk en moeilijk te negeren.",
    clientFriendlyExplanation: "De site laadt traag. Bezoekers verwachten dat een pagina binnen drie seconden zichtbaar is; daarna haken ze af. Dit beïnvloedt ook de positie in Google.",
  },
  hasClearCTA: {
    title: "Geen duidelijke call-to-action",
    severity: "high",
    dimension: "website",
    whyItMatters: "Zonder een duidelijke vervolgstap haken bezoekers af die anders zouden hebben geconverteerd. De UX-aanpassing met de hoogste hefboom.",
    likelyImpact: "Kan geïnteresseerde bezoekers verliezen die niet weten wat de volgende stap is.",
    suggestedFix: "Plaats één duidelijke primaire actie boven de vouw (Boek nu / Vraag offerte aan / Bel). Herhaal op logische punten lager op de pagina.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 5 },
    outreachAngle: "Loop samen door de homepage en vraag wat de bedoelde volgende stap is — meestal onduidelijk.",
    clientFriendlyExplanation: "Bezoekers landen op de site en weten niet wat ze moeten doen. Een duidelijke primaire actie — zoals 'Boek nu' — toevoegen is een van de meest impactvolle aanpassingen.",
  },
  hasContactForm: {
    title: "Geen online contactformulier",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Niet iedereen wil direct bellen. Een formulier vangt intentie op die anders verloren gaat.",
    likelyImpact: "Kan leads missen die liever niet bellen.",
    suggestedFix: "Voeg een formulier van 3 velden toe (naam / e-mail / bericht). Een automatische bevestigingsmail helpt.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Wijs erop dat de enige contactoptie een telefoonnummer is — beperkend in 2026.",
    clientFriendlyExplanation: "Sommige klanten willen niet bellen voordat ze meer informatie hebben. Een eenvoudig contactformulier vangt die leads op die anders zonder contact zouden vertrekken.",
  },
  hasPhoneVisible: {
    title: "Telefoonnummer niet zichtbaar boven de vouw",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Lokale bezoekers willen vaak bellen. Een verborgen telefoonnummer geeft onnodige frictie.",
    likelyImpact: "Kan ongeduldige of mobiele bezoekers verliezen.",
    suggestedFix: "Toon het telefoonnummer prominent in de header. Maak het op mobiel een tap-to-call-link.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Het telefoonnummer is lastig te vinden — bezoekers scrollen er niet voor.",
    clientFriendlyExplanation: "Het telefoonnummer is lastig te vinden. Voor een lokaal bedrijf is bellen vaak de snelste route naar een boeking — direct zichtbaar maken is een quick win.",
  },
  hasGoogleMapsLink: {
    title: "Geen kaart of adresverwijzing",
    severity: "low",
    dimension: "website",
    whyItMatters: "Klanten checken vaak of een bedrijf echt is door de kaart en reviews te bekijken.",
    likelyImpact: "Kan vertrouwen bij nieuwe bezoekers verminderen.",
    suggestedFix: "Embed een Google Maps-kaart van de locatie of link naar het Google Bedrijfsprofiel.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Combineer dit met de status van het Google Bedrijfsprofiel.",
    clientFriendlyExplanation: "Een kaart helpt klanten te bevestigen dat je echt bent en je locatie te vinden. Een kleine wijziging die het vertrouwen merkbaar kan vergroten.",
  },
  hasTrustSignals: {
    title: "Geen reviews of vertrouwenssignalen",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Reviews zijn de sterkste overtuigingshefboom voor lokale dienstverleners.",
    likelyImpact: "Kan bezoekers verliezen die concurrenten met reviews zien.",
    suggestedFix: "Voeg een Google-review-widget toe of plaats 3–5 klantbeoordelingen op de homepage.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Reviews zijn overtuigingsgoud — makkelijke toevoeging, zichtbaar verschil.",
    clientFriendlyExplanation: "Klanten vergelijken jou met concurrenten. Als hun site reviews toont en de jouwe niet, begin je elke vergelijking op achterstand.",
  },
  hasServicePages: {
    title: "Geen aparte dienstpagina's",
    severity: "medium",
    dimension: "website",
    whyItMatters: "Elke dienst heeft een eigen zoekintentie. Alles op één pagina laat tientallen long-tail zoekwoorden liggen.",
    likelyImpact: "Kan zichtbaarheid in zoekresultaten beperken voor afzonderlijke diensten.",
    suggestedFix: "Maak één pagina per hoofddienst, met gerichte tekst en een dienst-specifieke CTA.",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 12 },
    outreachAngle: "Combineer met lokale SEO — dienstpagina's zijn de basis daarvan.",
    clientFriendlyExplanation: "Op dit moment ziet Google één pagina over alles. Met aparte pagina's per dienst kan elk daarvan op zijn eigen zoekopdrachten ranken.",
  },
  hasCityLandingPage: {
    title: "Geen stad- of regiopagina",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "Lokale bedrijven concurreren op '[dienst] in [stad]'-zoekopdrachten. Zonder een stadgerichte pagina concurreer je tegen landelijke resultaten.",
    likelyImpact: "Kan lokale zoekkansen mislopen.",
    suggestedFix: "Maak een [Dienst] in [Stad]-pagina met locatie-specifieke tekst en reviews.",
    difficulty: "medium",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Frame als gemiste lokale SEO-kans — concreet en lokaal.",
    clientFriendlyExplanation: "Wanneer iemand zoekt op '[dienst] in [stad]', wil je het antwoord zijn. Een aparte lokale pagina vertelt Google dat je specifiek dat gebied bedient.",
  },

  // ── SEO ─────────────────────────────────────────────────────────────
  hasLocalSEOTitle: {
    title: "Paginatitel mist stad + dienst",
    severity: "high",
    dimension: "seo",
    whyItMatters: "De titel-tag is het sterkste lokale SEO-signaal dat Google leest.",
    likelyImpact: "Kan onzichtbaar maken voor lokale zoekopdrachten die makkelijke winsten zouden zijn.",
    suggestedFix: "Herschrijf naar het format: '[Dienst] in [Stad] — [Bedrijfsnaam]'.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "View Source op de homepage — de ontbrekende lokale titel is concreet en makkelijk te tonen.",
    clientFriendlyExplanation: "De paginatitel — wat je in de blauwe link in Google ziet — vermeldt niet wat je doet of waar. Dat is het eerste signaal dat Google gebruikt om je lokaal te ranken.",
  },
  hasMetaDescription: {
    title: "Geen meta-omschrijving",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "Zonder meta-omschrijving schrijft Google er zelf één — meestal slecht. Beïnvloedt clickthrough, niet direct de ranking.",
    likelyImpact: "Kan klikken vanuit zoekresultaten missen, zelfs bij goede positie.",
    suggestedFix: "Schrijf een omschrijving van ~150 tekens met hoofddienst, stad en een zachte hook.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Eenvoudige quick win — combineer met de titelfix.",
    clientFriendlyExplanation: "De grijze tekst die Google onder je link toont, is automatisch gegenereerd en vaak weinig nuttig. Zelf schrijven verbetert de doorklikratio.",
  },
  hasH1: {
    title: "Ontbrekende of dubbele H1-kop",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "De H1 vertelt Google waar elke pagina primair over gaat. Geen H1 is een basis SEO-misser.",
    likelyImpact: "Kan ranking-signalen op paginaniveau verzwakken.",
    suggestedFix: "Stel één beschrijvende H1 per pagina in die de dienst of het onderwerp benoemt.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Bundel met algemene opschoning van de heading-structuur.",
    clientFriendlyExplanation: "Elke pagina moet Google duidelijk vertellen waar het over gaat. Eén beschrijvende kop bovenaan doet dat.",
  },
  hasHeadingStructure: {
    title: "Inconsistente heading-hiërarchie",
    severity: "low",
    dimension: "seo",
    whyItMatters: "H1 → H2 → H3 helpt zowel screenreaders als Google de inhoud te begrijpen.",
    likelyImpact: "Kan toegankelijkheid en SEO subtiel benadelen.",
    suggestedFix: "Herstructureer headings: één H1, H2 per sectie, H3 per subsectie.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Polishpunt — neem mee in een bredere content-opschoning.",
    clientFriendlyExplanation: "De headings op de site zijn inconsistent, wat de pagina lastiger maakt voor Google en toegankelijkheidstools.",
  },
  hasLocalKeywords: {
    title: "Lokale zoekwoorden ontbreken in tekst",
    severity: "medium",
    dimension: "seo",
    whyItMatters: "Als de tekst de stad of regio niet noemt, concurreer je landelijk in plaats van lokaal.",
    likelyImpact: "Kan makkelijke lokale zoekkansen mislopen.",
    suggestedFix: "Verwerk de stad, wijken en regio natuurlijk in de hoofdtekst. Niet stuffen.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Toon dat de homepage de stad niet noemt — concreet bewijs.",
    clientFriendlyExplanation: "De tekst noemt je stad niet. Wanneer iemand zoekt op '[dienst] in [jouw stad]', wil Google pagina's zien die die stad ook daadwerkelijk benoemen.",
  },
  hasInternalLinks: {
    title: "Weinig of geen interne links",
    severity: "low",
    dimension: "seo",
    whyItMatters: "Interne links verspreiden ranking-kracht en verhogen de tijd op de site.",
    likelyImpact: "Kan beperken hoe Google de site crawlt en rankt.",
    suggestedFix: "Link gerelateerde dienst- en stadpagina's onderling vanuit de body-tekst.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Polishpunt — pak op binnen een bredere SEO-sprint.",
    clientFriendlyExplanation: "Het onderling linken van eigen pagina's helpt Google te begrijpen welke inhoud belangrijk is en houdt bezoekers langer op de site.",
  },
  isIndexable: {
    title: "Site lijkt geblokkeerd voor zoekmachines",
    severity: "critical",
    dimension: "seo",
    whyItMatters: "Als Google de site niet kan indexeren, kan hij nergens op ranken. De meest catastrofale SEO-misser.",
    likelyImpact: "De site kan volledig onzichtbaar zijn in zoekresultaten.",
    suggestedFix: "Verwijder noindex-meta en robots.txt-blocks. Stuur sitemap in via Search Console. Verifieer crawl via URL Inspection.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Kritiek — open hiermee. Dit is de bevinding die direct aandacht trekt.",
    clientFriendlyExplanation: "De site lijkt Google te vertellen om hem niet te tonen. Dit is de belangrijkste fix — zonder dit doet de rest er niet toe.",
  },
  hasSchemaMarkup: {
    title: "Geen LocalBusiness-schema",
    severity: "low",
    dimension: "seo",
    whyItMatters: "Schema-markup ontgrendelt rich results in Google (openingstijden, reviews, adres).",
    likelyImpact: "Kan rich-result-kansen mislopen die concurrenten benutten.",
    suggestedFix: "Voeg LocalBusiness JSON-LD toe met openingstijden, adres, telefoon, geo en review-schema.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Toon concurrenten met rich results — concrete onderscheiding.",
    clientFriendlyExplanation: "Gestructureerde data toevoegen vertelt Google specifieke info over je bedrijf — openingstijden, telefoon, adres — die direct in de zoekresultaten kan verschijnen.",
  },
  hasGoogleBusinessProfile: {
    title: "Lacune in Google Bedrijfsprofiel",
    severity: "critical",
    dimension: "seo",
    whyItMatters: "Het Bedrijfsprofiel is de belangrijkste lokale SEO-asset. Onclaim of leeg = grootste lokale zichtbaarheidsmisser.",
    likelyImpact: "Kan onzichtbaar zijn op Google Maps en in lokale resultaten.",
    suggestedFix: "Claim het profiel, vul alle velden, voeg 10+ foto's en diensten toe, vraag 5+ reviews aan bestaande klanten.",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 12 },
    outreachAngle: "Open hiermee voor elk lokaal bedrijf. Universele behoefte, grote zichtbare impact.",
    clientFriendlyExplanation: "Het Google Bedrijfsprofiel — de paneel naast je vermelding in zoekresultaten — heeft werk nodig. Dit is de grootste lokale-zoekhefboom voor elk bedrijf.",
  },

  // ── Conversion ──────────────────────────────────────────────────────
  hasClearOffer: {
    title: "Aanbod niet duidelijk binnen 5 seconden",
    severity: "high",
    dimension: "conversion",
    whyItMatters: "Als een bezoeker niet binnen seconden ziet wat je verkoopt, vertrekken ze. Het duurste UX-probleem.",
    likelyImpact: "Kan betrokkenheid op elke paginabezoek verminderen.",
    suggestedFix: "Herschrijf de hero zodat dienst + doelgroep + waarde in één zin duidelijk zijn.",
    difficulty: "medium",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Open de pagina en vraag: in 5 seconden, wat doet dit bedrijf? Antwoord is meestal onduidelijk.",
    clientFriendlyExplanation: "Wanneer iemand op de homepage komt, moet binnen vijf seconden duidelijk zijn wat je doet, voor wie en waarom het ertoe doet. Op dit moment is dat niet helder.",
  },
  lowContactFriction: {
    title: "Contact opnemen kost te veel stappen",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "Elk extra veld of elke extra klik kost een percentage leads. Frictie is de stille conversiekiller.",
    likelyImpact: "Kan leads verliezen die wel begonnen maar niet voltooiden.",
    suggestedFix: "Beperk contactopname tot 3 velden. Voeg op mobiel een one-click bel-CTA toe.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Loop samen het contactproces door — meestal 5+ stappen.",
    clientFriendlyExplanation: "Op dit moment kost contact opnemen meer stappen dan nodig. Elke extra stap kost stilletjes een percentage leads.",
  },
  lowBookingFriction: {
    title: "Boeken vraagt handmatig heen-en-weer",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "Self-service-boekingen vangen klanten buiten kantoortijden en verminderen administratie.",
    likelyImpact: "Kan boekingen na sluitingstijd volledig mislopen.",
    suggestedFix: "Voeg een online boekingswidget toe voor de meest gevraagde dienst.",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 8 },
    outreachAngle: "Frame als zowel klantbeleving als tijdsbesparing.",
    clientFriendlyExplanation: "Klanten kunnen zichzelf niet boeken; ze moeten mailen of bellen. Dat betekent dat je de mensen mist die laat 's avonds beslissen, en het levert jou extra administratie op.",
  },
  hasAboveFoldCTA: {
    title: "Primaire CTA verborgen onder de vouw",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "De meeste bezoekers scrollen niet. Een CTA onder de vouw is in feite onzichtbaar voor de helft van het publiek.",
    likelyImpact: "Kan bezoekers verliezen die niet scrollen.",
    suggestedFix: "Plaats de hoofd-CTA in de hero-sectie, zichtbaar zonder scrollen.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 2 },
    outreachAngle: "Open op desktop EN mobiel — toon de ontbrekende CTA in beide weergaven.",
    clientFriendlyExplanation: "De actie die je wilt dat bezoekers nemen, moet zichtbaar zijn zonder dat ze hoeven scrollen. Op dit moment moeten ze ervoor scrollen — velen doen dat niet.",
  },
  hasMobileCTA: {
    title: "Geen sticky / tap-to-call CTA op mobiel",
    severity: "medium",
    dimension: "conversion",
    whyItMatters: "Mobiele gebruikers scrollen niet terug naar een CTA bovenaan. Een blijvende onderkant-actie houdt het pad open.",
    likelyImpact: "Kan mobiele bezoekers verliezen die opgeven met scrollen.",
    suggestedFix: "Voeg een sticky tap-to-call of 'Boek nu'-knop toe onderaan het mobiele beeldscherm.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Concreet en mobiel-specifiek — makkelijk te tonen.",
    clientFriendlyExplanation: "Op mobiel verdwijnt de actieknop zodra bezoekers scrollen. Een sticky onderkant-knop houdt de route naar contact altijd zichtbaar.",
  },
  hasLeadCapture: {
    title: "Geen zachte lead-capture",
    severity: "low",
    dimension: "conversion",
    whyItMatters: "De meeste bezoekers zijn nog niet klaar om te committen. Een zachte capture (gratis offerte / nieuwsbrief) vangt het tussenstuk op.",
    likelyImpact: "Kan de 90% bezoekers missen die nog niet klaar zijn om te kopen.",
    suggestedFix: "Voeg een gratis-offerte- of inschattingsformulier toe als laagdrempelig alternatief.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Frame als het opvangen van long-tail-leads die anders zouden verdwijnen.",
    clientFriendlyExplanation: "De meeste bezoekers zijn vandaag nog niet klaar om te boeken. Iets laagdrempeligs aanbieden — zoals een gratis offerte — vangt degenen op die anders zonder iets zouden vertrekken.",
  },

  // ── Automation ──────────────────────────────────────────────────────
  hasBookingAutomation: {
    title: "Geen online boekingssysteem",
    severity: "high",
    dimension: "automation",
    whyItMatters: "Handmatige boekingen kosten uren en beperken wanneer klanten zichzelf kunnen helpen.",
    likelyImpact: "Kan 24/7-boekkansen missen + administratie-uren kosten.",
    suggestedFix: "Zet een boekingswidget op (Calendly / Setmore / Square / niche-tool).",
    difficulty: "medium",
    implementation: { minHours: 4, maxHours: 8 },
    outreachAngle: "Open met de tijdwinst — meestal 5+ uur per week terug.",
    clientFriendlyExplanation: "Op dit moment vraagt elke boeking heen-en-weer. Een online boekingswidget laat klanten zichzelf helpen buiten kantoortijden en bespaart enkele uren per week.",
  },
  hasQuoteAutomation: {
    title: "Geen offerte-automatisering",
    severity: "medium",
    dimension: "automation",
    whyItMatters: "Offerteverzoeken die wachten worden koud. Een automatische bevestiging houdt ze warm.",
    likelyImpact: "Kan offerte-leads verliezen aan snellere concurrenten.",
    suggestedFix: "Bouw een offerteformulier met automatische ontvangstbevestiging + verwachte responstijd.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 4 },
    outreachAngle: "Frame als 'laat geen lead koud worden' — universeel aansprekend.",
    clientFriendlyExplanation: "Wanneer iemand een offerte aanvraagt, wil diegene direct bevestiging. Een automatische bevestiging houdt ze betrokken terwijl jij het echte antwoord voorbereidt.",
  },
  hasInvoiceAutomation: {
    title: "Handmatig factureren",
    severity: "medium",
    dimension: "automation",
    whyItMatters: "Handmatige facturen vertragen betalingen en kosten administratietijd.",
    likelyImpact: "Kan cashflow vertragen + uren boekhouding per week toevoegen.",
    suggestedFix: "Koppel Stripe / Moneybird / Exact om facturen automatisch te genereren en versturen bij oplevering.",
    difficulty: "medium",
    implementation: { minHours: 3, maxHours: 8 },
    outreachAngle: "Tijd + cashflow-invalshoek — beide kwantificeerbaar.",
    clientFriendlyExplanation: "Handmatig factureren vertraagt en stelt betalingen uit. Een geautomatiseerde tool koppelen verstuurt facturen direct en verkleint de adminlus.",
  },
  hasReminderEmails: {
    title: "Geen afspraakherinneringen",
    severity: "low",
    dimension: "automation",
    whyItMatters: "No-shows zijn duur. Geautomatiseerde herinneringen verlagen ze meestal met 30–50%.",
    likelyImpact: "Kan omzet kosten per gemiste afspraak.",
    suggestedFix: "Voeg SMS/e-mail-herinneringen 24u voor elke afspraak toe via het boekingssysteem.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Eenvoudige ROI-berekening — herinneringen verdienen zichzelf snel terug.",
    clientFriendlyExplanation: "Wanneer klanten afspraken vergeten, verlies je de plek én de omzet. Geautomatiseerde herinneringen verminderen no-shows aanzienlijk zonder handmatige inspanning.",
  },
  hasFollowUpAutomation: {
    title: "Geen lead-follow-up-automatisering",
    severity: "medium",
    dimension: "automation",
    whyItMatters: "De meeste leads reageren niet op het eerste bericht. Zonder follow-up zijn ze verloren.",
    likelyImpact: "Kan leads verliezen die op een tweede contactmoment zouden hebben geconverteerd.",
    suggestedFix: "Voeg een 2-stappen e-mailsequentie toe voor leads die niet binnen 3 dagen reageren.",
    difficulty: "easy",
    implementation: { minHours: 2, maxHours: 5 },
    outreachAngle: "Frame als de leads opvangen die anders door de mazen vallen.",
    clientFriendlyExplanation: "De meeste leads reageren niet op de eerste poging. Een eenvoudige twee-stappen follow-up vangt degenen op die een vriendelijke herinnering nodig hadden.",
  },
  hasAnalytics: {
    title: "Geen analytics geïnstalleerd",
    severity: "low",
    dimension: "automation",
    whyItMatters: "Zonder analytics is elke marketingbeslissing een gok.",
    likelyImpact: "Kan ervoor zorgen dat beslissingen blind worden genomen.",
    suggestedFix: "Installeer GA4 + Google Search Console. Voeg event-tracking toe op belangrijke CTA's.",
    difficulty: "easy",
    implementation: { minHours: 1, maxHours: 3 },
    outreachAngle: "Snelle fundamentele fix — bundel binnen elk project.",
    clientFriendlyExplanation: "Op dit moment is er geen manier om te zien wat werkt op de site. Analytics toevoegen laat je beslissen op basis van echte data in plaats van gokken.",
  },
  hasInternalDashboard: {
    title: "Geen team-dashboard",
    severity: "low",
    dimension: "automation",
    whyItMatters: "Een klein dashboard met de boekingen van vandaag, leads en kerncijfers bespaart dagelijkse frictie.",
    likelyImpact: "Kan administratietijd kosten met zoeken naar dagelijkse info.",
    suggestedFix: "Bouw een klein intern dashboard dat boekingen van vandaag + recente leads in één weergave toont.",
    difficulty: "medium",
    implementation: { minHours: 6, maxHours: 16 },
    outreachAngle: "Premium-add-on — focus op grotere klanten.",
    clientFriendlyExplanation: "Een eenvoudig gedeeld dashboard voor je team — boekingen van vandaag, recente leads, kerncijfers — bespaart dagelijkse frictie en geeft iedereen dezelfde weergave.",
  },
};
